#define MSG_OK                          "Éxito."
#define MSG_ERROR_NULL_POINTER          "Se intentó desreferenciar un puntero nulo."
#define MSG_ERROR_MEMORY                "No se pudo reservar memoria."
#define MSG_ERROR_UNKNOWN_FILE_FORMAT   "Formato de archivo desconocido."
#define MSG_ERROR_INVALID_LINE          "El archivo NMEA contiene una línea inválida."
#define MSG_ERROR_OPENING_NMEA_FILE     "Al abrir el archivo NMEA."
#define MSG_ERROR_OPENING_CONFIG_FILE   "Al abrir un archivo de configuración."
#define MSG_ERROR_OPENING_OUTPUT_FILE   "Al crear el archivo de salida."
#define MSG_ERROR_READING_NMEA_FILE     "Al leer el archivo NMEA."
#define MSG_ERROR_READING_CONFIG_FILE   "Al leer un archivo de configuración."
#define MSG_ERROR_WRITING_OUTPUT_FILE   "Al escribir el archivo de salida."
#define MSG_ERROR_PROGRAM_INVOCATION    "Fallo en la invocación del programa."
#define MSG_ERROR_CORRUPT_NMEA_FILE     "El archivo NMEA está corrupto."
#define MSG_ERROR_PARSING_LATITUDE      "Al parsear la latitud."
#define MSG_ERROR_PARSING_LONGITUDE     "Al parsear la longitud."
#define MSG_ERROR_PARSING_ALTITUDE      "Al parsear la altura."
#define MSG_ERROR_PARSING_FIX_QUALITY   "Al parsear el indicador de posición fija."

#define MSG_USAGE   "Uso"
