#define MSG_OK                          "Success."
#define MSG_ERROR_NULL_POINTER          "Tried to dereference a null pointer"
#define MSG_ERROR_MEMORY                "Couldn't allocate memory."
#define MSG_ERROR_UNKNOWN_FILE_FORMAT   "Unknown file format."
#define MSG_ERROR_INVALID_LINE          "The NMEA file contained an invalid line."
#define MSG_ERROR_OPENING_NMEA_FILE     "While opening the NMEA file."
#define MSG_ERROR_OPENING_CONFIG_FILE   "While opening a config file."
#define MSG_ERROR_OPENING_OUTPUT_FILE   "While creating the output file."
#define MSG_ERROR_READING_NMEA_FILE     "While reading the NMEA file."
#define MSG_ERROR_READING_CONFIG_FILE   "While reading a config file."
#define MSG_ERROR_WRITING_OUTPUT_FILE   "While writing the output file."
#define MSG_ERROR_PROGRAM_INVOCATION    "Wrong command line parameters."
#define MSG_ERROR_CORRUPT_NMEA_FILE     "The NMEA file was corrupt."
#define MSG_ERROR_PARSING_LATITUDE      "While parsing the latitude."
#define MSG_ERROR_PARSING_LONGITUDE     "While parsing the longitude."
#define MSG_ERROR_PARSING_ALTITUDE      "While parsing the altitude."
#define MSG_ERROR_PARSING_FIX_QUALITY   "While parsing the fix quality."

#define MSG_USAGE   "Usage"
